### ISSUE TITLE
App contains errors if opened in Studio with other language than English

### ISSUE THREAD

**Issue by e-gallis** [thatapiguy/Dataverse-Admin#1]
Hi @thatapiguy, frist of all: real nice job there! I immediately opened your app to see its core.
Unfortunately I had a lot of errors in it because my Studio is in French and many of the fields or table names were not recognized by Power Apps since their display name aren't the same in different languages:
![image](https://user-images.githubusercontent.com/32480338/154937076-21cb3cd6-d0c2-4003-916d-bba2b19a294f.png)

I really don't understand why Power Apps doesn't store datasource elements using their internal name and then show the display name in the formula bar using the Studio language. This is really a pain...

Any feedback/ideas on this?

**Comment by thatapiguy** [comment]
Hi. Thanks for submitting the feedback. This really sucks. I thought Power Apps would take care of the language related changes automatically, however, that doesn't seem to be the case.
Let me check with some other PowerAddicts and maybe ask someone at Microsoft who could help with this.

**Comment by thatapiguy** [comment]
@e-gallis can you try changing the Studio language to English before importing , then save the app and then change the language back to French?

**Comment by e-gallis** [comment]
> @e-gallis can you try changing the Studio language to English before importing , then save the app and then change the language back to French?

Honestly, I really doubt this will change anything as I will be saving the app in English and going back to French should just show up the same errors as all tables and fields will be back to French... But I'll give it a try...

**Comment by thatapiguy** [comment]
Doesn't look like I will have a solution to this. So going to close this. Sorry!
